### ISSUE TITLE
Nether Hammer Loading Error

### ISSUE THREAD

**Issue by dranorter** [Draylar/vanilla-hammers#12]
I get an error upon loading:

error Parsing error loading recipe vanilla-hammers:nether_hammer
com.google.gson.JsonSyntaxException: Unknown item 'vanilla-hammers:nether_hammer'

I can't see why this would happen, since obviously the other hammer recipes all refer to themselves in the same way but load fine.

**Comment by Draylar** [comment]
This _should_ be better in the 1.4.2 version. Are you using it? A full log would also be great.

It's erroring because the Nether Hammer is a cross-feature with _Nether Things_, and the item is only registered if the latter mod is loaded. It's nothing to worry about, but I do hope to censor it fully (and 1.4.2 almost does that).

Thanks for the report!

**Comment by dranorter** [comment]
Ah, that makes sense. Nether Things doesn't look like something I want at the moment, and I see why you'd tie it to that.

I'm using 1.4.1.

Here's a more complete log, though probably you don't need it.

```
[0630/142712:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_3304 (Server thread) info Reloading ResourceManager: Vanilla Hammers, Mpcs' Backpacks, Illuminations, Extra Pieces, fabric-mining-levels-v0, Default, FH better snow v1.1.0, Ships v5 for [1.14.2], breed-easy-datapack-1561093921, madscientist-1561107053, villager-hoppers-1558858065

[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_1863 (Server thread) error Parsing error loading recipe vanilla-hammers:glowstone_hammer
com.google.gson.JsonSyntaxException: Unknown item 'netherthings:glowstone_ingot'
	at net.minecraft.class_1856.method_17873(class_1856.java:162)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.minecraft.class_1856.method_8107(class_1856.java:162)
	at net.minecraft.class_1856.method_8102(class_1856.java:144)
	at net.minecraft.class_1869.method_8157(class_1869.java:225)
	at net.minecraft.class_1869.method_8159(class_1869.java:24)
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246)
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241)
	at net.minecraft.class_1863.method_17720(class_1863.java:115)
	at net.minecraft.class_1863.method_20705(class_1863.java:53)
	at net.minecraft.class_1863.method_18788(class_1863.java:34)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_18857(class_1255.java:123)
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1460)
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:449)
	at net.minecraft.class_1132.method_3735(class_1132.java:79)
	at net.minecraft.class_1132.method_3823(class_1132.java:104)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
	at java.lang.Thread.run(Thread.java:748)


[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_1863 (Server thread) error Parsing error loading recipe vanilla-hammers:nether_hammer
com.google.gson.JsonSyntaxException: Unknown item 'vanilla-hammers:nether_hammer'
	at net.minecraft.class_1869.method_17878(class_1869.java:233)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.minecraft.class_1869.method_8155(class_1869.java:233)
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:254)
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241)
	at net.minecraft.class_1863.method_17720(class_1863.java:115)
	at net.minecraft.class_1863.method_20705(class_1863.java:53)
	at net.minecraft.class_1863.method_18788(class_1863.java:34)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_18857(class_1255.java:123)
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1460)
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:449)
	at net.minecraft.class_1132.method_3735(class_1132.java:79)
	at net.minecraft.class_1132.method_3823(class_1132.java:104)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
	at java.lang.Thread.run(Thread.java:748)


[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_1863 (Server thread) error Parsing error loading recipe vanilla-hammers:vibranium_hammer
com.google.gson.JsonSyntaxException: Unknown item 'netherthings:vibranium_block'
	at net.minecraft.class_1856.method_17873(class_1856.java:162)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.minecraft.class_1856.method_8107(class_1856.java:162)
	at net.minecraft.class_1856.method_8102(class_1856.java:144)
	at net.minecraft.class_1869.method_8157(class_1869.java:225)
	at net.minecraft.class_1869.method_8159(class_1869.java:24)
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246)
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241)
	at net.minecraft.class_1863.method_17720(class_1863.java:115)
	at net.minecraft.class_1863.method_20705(class_1863.java:53)
	at net.minecraft.class_1863.method_18788(class_1863.java:34)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_18857(class_1255.java:123)
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1460)
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:449)
	at net.minecraft.class_1132.method_3735(class_1132.java:79)
	at net.minecraft.class_1132.method_3823(class_1132.java:104)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
	at java.lang.Thread.run(Thread.java:748)


[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_1863 (Server thread) error Parsing error loading recipe vanilla-hammers:tater_hammer
com.google.gson.JsonSyntaxException: Unknown item 'lil-tater:lil_tater'
	at net.minecraft.class_1856.method_17873(class_1856.java:162)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at net.minecraft.class_1856.method_8107(class_1856.java:162)
	at net.minecraft.class_1856.method_8102(class_1856.java:144)
	at net.minecraft.class_1869.method_8157(class_1869.java:225)
	at net.minecraft.class_1869.method_8159(class_1869.java:24)
	at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246)
	at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241)
	at net.minecraft.class_1863.method_17720(class_1863.java:115)
	at net.minecraft.class_1863.method_20705(class_1863.java:53)
	at net.minecraft.class_1863.method_18788(class_1863.java:34)
	at net.minecraft.class_4080.method_18790(class_4080.java:13)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at net.minecraft.class_4014.method_18365(class_4014.java:71)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:135)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:114)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:701)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:695)
	at net.minecraft.class_1255.method_18857(class_1255.java:123)
	at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1460)
	at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:449)
	at net.minecraft.class_1132.method_3735(class_1132.java:79)
	at net.minecraft.class_1132.method_3823(class_1132.java:104)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
	at java.lang.Thread.run(Thread.java:748)


[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_1863 (Server thread) info Loaded 6 recipes

[0630/142715:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_2991 (Server thread) info Loaded 34 custom command functions

[0630/142716:INFO:GameCallbacks.cpp(198)] game/net.minecraft.class_163 (Server thread) info Loaded 817 advancements

[0630/142716:INFO:GameCallbacks.cpp(198)] game/net.minecraft.server.MinecraftServer (Server thread) info Preparing start region for dimension minecraft:overworld
```
