### ISSUE TITLE
1.19 Update (+my attempt at it)

### ISSUE THREAD

**Issue by builderpepc** [Draylar/vanilla-hammers#124]
I'm not experienced at all with Minecraft mod development or anything major in Java, but I attempted to upgrade the mod for 1.19 based on previous commits and upgrading guides. You can take a look [here](https://github.com/builderpepc/vanilla-hammers/tree/1.19). 

I'd be willing to make a PR if I did everything right, but I think something with the dependency `magna` is causing a crash upon attempting to use the hammers (they do load, and the hitbox shows; crash report [here](https://github.com/Draylar/vanilla-hammers/files/8944912/crash-2022-06-20_21.04.13-server.txt)), and I don't really know how to go about fixing that. Hope an update comes soon!

For ease of viewing, here is the error stack trace:
```java
java.lang.NoSuchMethodError: 'void net.minecraft.class_2680.method_26180(net.minecraft.class_3218, net.minecraft.class_2338, net.minecraft.class_1799)'
	at draylar.magna.api.BlockBreaker.breakInRadius(BlockBreaker.java:122)
	at draylar.magna.api.MagnaTool.attemptBreak(MagnaTool.java:142)
	at net.minecraft.class_3225.handler$zjb000$tryBreak(class_3225.java:1038)
	at net.minecraft.class_3225.method_14266(class_3225.java:255)
	at net.minecraft.class_3225.method_21717(class_3225.java:228)
	at net.minecraft.class_3225.method_14263(class_3225.java:203)
	at net.minecraft.class_3244.method_12066(class_3244.java:1062)
	at net.minecraft.class_2846.method_12361(class_2846.java:42)
	at net.minecraft.class_2846.method_11054(class_2846.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Sheep7798** [comment]
I think there is a crash because magna isn't up to date, some people made a 1.19 version of it I think

**Comment by anwen-anyi** [comment]
> I think there is a crash because magna isn't up to date, some people made a 1.19 version of it I think

**excuse me Did you find the version 1.19.x(2)?**

**Comment by Sheep7798** [comment]
https://github.com/PTOM76/magna/tree/1.19

**Comment by anwen-anyi** [comment]
> https://github.com/PTOM76/magna/tree/1.19

**thanks**
