### ISSUE TITLE
Error Loading recipe on fabric 1.14 b7; loader 0.4.6; binary 141 and fabric 1.14 b2; loader 0.4.4; binary 137

### ISSUE THREAD

**Issue by VegethB** [Draylar/vanilla-hammers#4]
It is also repeated for extra materials (if disabled). I get the same error also by putting "false" on the tater slot.

Thanks in advance.

CMD Output:

[13:48:49] [Server thread/ERROR]: Parsing error loading recipe vanilla-hammers:tater_hammer
com.google.gson.JsonSyntaxException: Unknown item 'lil-tater:lil_tater'
        at net.minecraft.class_1856.method_17873(class_1856.java:162) ~[intermediary-server.jar:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[intermediary-server.jar:?]
        at net.minecraft.class_1856.method_8102(class_1856.java:144) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-server.jar:?]
        at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_17720(class_1863.java:139) ~[intermediary-server.jar:?]
        at net.minecraft.class_1863.method_14491(class_1863.java:61) ~[intermediary-server.jar:?]
        at net.minecraft.class_4013.method_18235(class_4013.java:12) ~[intermediary-server.jar:?]
        at java.util.concurrent.CompletableFuture.uniRun(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$UniRun.tryFire(Unknown Source) ~[?:1.8.0_201]
        at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
        at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:135) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:114) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:123) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1466) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:450) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:366) [intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3823(class_3176.java:218) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:605) [intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Draylar** [comment]
I would recommend installing https://minecraft.curseforge.com/projects/suppress-unknown-item for now until I find a better solution.
