### ISSUE TITLE
Warnings in game log using the latest version 1.10.1 for 1.16.1

### ISSUE THREAD

**Issue by linzexin022** [Draylar/vanilla-hammers#65]
Hello there, I found some warnings in game log:

`[15:52:51] [main/INFO]: [STDERR]: java.lang.ClassNotFoundException: com.github.draylar.vh.api.HammerItem
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.Class.forName(Class.java:340)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.VanillaHammersIntegration.<clinit>(VanillaHammersIntegration.java:41)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:85)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.registerBlock(BlocksRegistry.java:433)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:28)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:30)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:425)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:52:51] [main/INFO]: [STDERR]: java.lang.NullPointerException
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.VanillaHammersIntegration.makeHammer(VanillaHammersIntegration.java:24)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:85)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.registerBlock(BlocksRegistry.java:433)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:28)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:30)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:425)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:52:51] [main/INFO]: [STDERR]: java.lang.NullPointerException
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.VanillaHammersIntegration.makeHammer(VanillaHammersIntegration.java:24)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:86)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.registerBlock(BlocksRegistry.java:433)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:28)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:30)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:425)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[15:52:51] [main/INFO]: [STDERR]: java.lang.NullPointerException
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.VanillaHammersIntegration.makeHammer(VanillaHammersIntegration.java:24)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.ItemsRegistry.<clinit>(ItemsRegistry.java:87)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.registerBlock(BlocksRegistry.java:433)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.registry.BlocksRegistry.<clinit>(BlocksRegistry.java:28)
[15:52:51] [main/INFO]: [STDERR]: 	at paulevs.betternether.BetterNether.onInitialize(BetterNether.java:30)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:425)
[15:52:51] [main/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:177)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
[15:52:51] [main/INFO]: [STDERR]: 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:52:51] [main/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[15:52:51] [main/INFO]: [STDERR]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)`

**Comment by Draylar** [comment]
Mm, yeah, I basically entirely broke mod compatibility with the latest update (Better Nether is the mod erroring, as they previously reflected into the Vanilla Hammers mod to add hammers).  I might be able to send them a fix PR in the next week or so.

**Comment by linzexin022** [comment]
OK, thank you for your reply!
