### ISSUE TITLE
Tweakers

### ISSUE THREAD

**Issue by psecegm** [Draylar/vanilla-hammers#76]
First and foremost, **THANK YOU** for creating and maintaining this mod!  I know its a lot of blood, sweat and tears!  I really love this mod and miss it greatly when its not available.  And I hope that I am not wasting your time on this with something that I missed!

Vanilla-Hammers 2.0.6-1.16.2

Recently, I updated to a MineCraft 1.16.2 instance and I think there may be an issue with the use of LibCD.  I am getting a NoClassDefFoundError with the latest releases of Fabric and Hammers:  Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/libcd/api/tweaker/Tweaker.  When I looked at the latest version of LibContainerData (And what version it looks like Hammers Gradle is referencing), it looks like Tweaker code has been removed.  Looking through your code, I don't see any direct references to Tweaker.  But I do see your LibCD usage in the configurations which leads me to think its in the realm of either LibContainerData or a bad mix of Fabric versions (early Minecraft Version updates).  But when debugging, you start at the top and work your way deeper....  

### Changes that I have tried to fix the issue:

(All have been done thru MultiMC)
Added the libcd-3.0.2+1.16.2.jar to the loader mods.
Downgraded Fabric API to the gradle version:  fabric-api-0.19.0+build.398-1.16.jar to fabric-api-0.18.0+build.397-1.16.jar

### Crash Report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 8/23/20, 9:23 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'libcd'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'libcd' provided by 'techreborn'
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:163)
	at net.fabricmc.loader.FabricLoader.getEntrypoints(FabricLoader.java:246)
	at io.github.cottonmc.libcd.LibCD.onInitialize(LibCD.java:33)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.NoClassDefFoundError: io/github/cottonmc/libcd/api/tweaker/Tweaker
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114)
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101)
	at net.fabricmc.loader.EntrypointStorage.getEntrypoints(EntrypointStorage.java:156)
	... 22 more
Caused by: java.lang.ClassNotFoundException: io.github.cottonmc.libcd.api.tweaker.Tweaker
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 28 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:423)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 5.4.0-7642-generic
	Java Version: 11.0.8, Ubuntu
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Ubuntu
	Memory: 256663552 bytes (244 MB) / 850395136 bytes (811 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms512m -Xmx1024m
	Fabric Mods: 
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		blue_endless_jankson: jankson +
		chainmail: Chainmail 0.3.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.8
		cloth-config2: Cloth Config v4 4.7.0-unstable
		creativebuttonmover: Creative Button Mover 0.2.5
		diggusmaximus: Diggus Maximus 1.3.1-1.16
		expandedstorage: ExpandedStorage 5.3.16
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		glassdoor: Glass Doors 1.4.4-1.16
		gravestones: Gravestones 1.4.0
		harvest: Harvest 1.2.12
		improved-stations: Improved Stations 2.0.3
		inventorysorter: Inventory Sorter 1.7.2-1.16
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.2-1.16
		libblockattributes: LibBlockAttributes 0.7.0
		libblockattributes_core: LibBlockAttributes (Core) 0.7.0
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.7.0
		libblockattributes_items: LibBlockAttributes (Items) 0.7.0
		libcd: LibCapableData 3.0.2+1.16.2
		libmultipart: LibMultiPart 0.4.0
		libnetworkstack: Lib Network Stack 0.4.0
		libstructure: LibStructure 1.5
		magna: Magna 1.4.0-1.16.2
		minecraft: Minecraft 1.16.2
		modmenu: Mod Menu 1.14.6+build.31
		ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
		org_jetbrains_annotations: annotations 17.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
		reborncore: Reborn Core 4.4.0+build.67
		repurposed_structures: Repurposed Structures 1.5.1
		roughlyenoughitems: Roughly Enough Items 5.2.7
		roughlyenoughitems-api: REI (API) 5.2.7
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.2.7
		roughlyenoughitems-runtime: REI (Runtime) 5.2.7
		simple_pipes: SimplePipeTest 0.4.0
		simple_pipes_dep_container: SimplePipeTest (Dependency Container) 0.4.0
		staticdata: Static Data 1.1.2
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.5.1+build.101
		trees-do-not-float: Trees Do Not Float 1.12.94
		vanilla-hammers: Vanilla Hammers 2.0.6-1.16.2
		voxelmap: VoxelMap 1.10.10
		waila: Hwyla 1.9.22
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>

**Comment by Draylar** [comment]
IIRC, LibCD removed Tweakers in the 1.16.2 update (3.0.0+). VH doesn't touch them. Is there a chance another mod you have is using Tweakers while assuming the LibCD version is <= 1.16.1 (like, a mod that hasn't been fully updated to 1.16.2, but still "works")?
edit: [seems to be TechReborn](https://github.com/TechReborn/TechReborn/blob/2eef16080b509786a41fc01b70a727370595cf1f/build.gradle#L84):
`Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'libcd' provided by 'techreborn'`

**Comment by psecegm** [comment]
I am really sorry Draylar!   I have updated a thread that was left on Tech Reborn with the information...  Again, Thank you!

**Comment by Draylar** [comment]
Happy to help!
