### ISSUE TITLE
Game crashes when using any hammer in survival mode

### ISSUE THREAD

**Issue by JSJBDEV** [Draylar/vanilla-hammers#89]
A very crypic log, simply use any hammer on any hammerable block, in survival mode
```
java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_776.method_23071(class_776.java:46)
	at net.minecraft.class_761.method_22710(class_761.java:1319)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler$$Lambda$58/1388278453.accept(Unknown Source)
	at java.util.HashMap$Values.forEach(HashMap.java:972)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
```
this seems to also extend to the hammers added by astromine as well, it happens in both singleplayer and multiplayer and the server reckons its a class cast exception

**Comment by Vestak3321** [comment]
I am having this issue too.  Here's my crash report, hope it helps.

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_776.method_23071(class_776.java:46)
	at net.minecraft.class_761.method_22710(class_761.java:1319)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

**Comment by Draylar** [comment]
can you provide your full game log through a service such as pastebon?

**Comment by JSJBDEV** [comment]
I just tried readding it to my pack and got some really weird visual errors, I have  a feeling this my have been what was happening to start with and Im thinking perhaps this is a sodium bug? will try and get you a log of the Astromine hammers which appear to use the exact same code

**Comment by JSJBDEV** [comment]
[crash-2021-04-09_16.59.31-client.txt](https://github.com/Draylar/vanilla-hammers/files/6287052/crash-2021-04-09_16.59.31-client.txt)
[crash-2021-04-09_16.59.59-client.txt](https://github.com/Draylar/vanilla-hammers/files/6287053/crash-2021-04-09_16.59.59-client.txt)

**Comment by JSJBDEV** [comment]
these errors appear to be different then previous versions, but again It appears to be some kind of visual bug when holding the hammers in survival mode, Id guess sodium to be the main culprit

**Comment by Draylar** [comment]
Both logs give no information (cryptic, as you said), so it's hard to say what the problem is. Have you tried the game without Sodium? I'll try loading them both up tonight and see if I can reproduce the issue.

**Comment by JSJBDEV** [comment]
If I have a chance tonight ill test it without sodium, if you could do it also thatd be great

**Comment by ghost** [comment]
Here: [crash-log](https://pastebin.com/r128cQmZ)

Crash appears after hitting a stone with any hammer.

_Edit_

Next: [crash-log](https://pastebin.com/ANGn8Jh5)

Crash appears after hitting a coal ore with vibranium hammer.

_Edit_

Last: [crash-log](https://pastebin.com/peT1mtH5)

Crash appears in the same situation as above, but i run MC without Sodium & Indium.

**Comment by ghost** [comment]
Fixed - just change the "magna" config file;  "enableAllBlockBreakingAnimation" to false.

**Comment by JSJBDEV** [comment]
Yup it's a sodium thing otherwise from what I can tell

**Comment by JSJBDEV** [comment]
yeah so this happens without sodium as well so I will change the config file

**Comment by ghost** [comment]
Any new information about release fix?
new crashlog: https://pastebin.com/RE3Rea7N
